version: "3.8"
services:
    web:
        build: .
        command: gunicorn -b 0.0.0.0:5000 backend.wsgi:app
        volumes:
            - ./backend/:/usr/src/app/
        ports:
            - 5000:5000
        environment:
            - DB_NAME=boomberg
            - DB_USER=postgres
            - DB_PASSWORD=admin123
            - DB_HOST=pg
            - DB_PORT=5432
            - DATABASE=postgres
        depends_on:
            - pg
    pg:
        container_name: pg_container_boomberg
        image: postgres:14.1-alpine3.15
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin123
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - "5432:5432"
        volumes:
            - "${PWD}/backend/database/initdb/:/docker-entrypoint-initdb.d/"

    pgadmin:
        container_name: pgadmin_container_boomberg
        image: dpage/pgadmin4:6.4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin123
            PGADMIN_LISTEN_PORT: 5433
            PGADMIN_CONFIG_SERVER_MODE: "False"
            PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
            PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
        ports:
            - "5433:5433"
        depends_on:
            - pg
        volumes:
            - pgadmin_data:/var/lib/pgadmin

volumes:
    pgadmin_data:
